package com.bank.utlis;

public enum StatusCode {

	YOUR_REQUEST_SUCCESSFUL,
	YOUR_REQUEST_FAILURE,
	YOUR_ACCOUNT_CREATED,
	YOUR_REQUEST_PENDING,
	YOUR_REQUEST_IN_PROCESSING,
	USER_DONT_HAVE_ACCOUNT
	
}
